volumes:
  prom:
  grafana-data:

services:

  node-exporter:
    build:
      context: ../node_exporter
      args:
        arch: ${ARCH:-amd64}
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring

  prometheus:
    build:
      context: ../prometheus
      args:
        arch: ${ARCH:-amd64}
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom:/prometheus
    networks:
      - monitoring
    depends_on:
      - node-exporter

  grafana:
    build:
      context: ../grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
