volumes:
  prom:
  grafana-data:

services:

  node-exporter:
    image: europe-north2-docker.pkg.dev/build-project-476008/monitoring/node:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring

  prometheus:
    image: europe-north2-docker.pkg.dev/build-project-476008/monitoring/prom:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom:/prometheus
    networks:
      - monitoring
    depends_on:
      - node-exporter

  grafana:
    image: europe-north2-docker.pkg.dev/build-project-476008/monitoring/graf:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./datasources.yml:/usr/share/grafana/conf/provisioning/datasources/datasources.yml:ro
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
