
#europe-north2-docker.pkg.dev/build-project-476008/monitoring/graf
#europe-north2-docker.pkg.dev/build-project-476008/monitoring/node
#europe-north2-docker.pkg.dev/build-project-476008/monitoring/prom

name: 'Terraform Push Workflow for Apply'
on:
  push:
    branches:
      - main
    paths:
      - 'ssh-vm/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ssh-vm

    steps:
      - uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA }}' 
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Apply
        run: terraform apply --auto-approve

      - name: SSH in the VM 
        run: gcloud compute ssh [USER@]my_instance --zone=us-central1-a --command='YOUR_COMMAND_HERE'