name: image-build-push

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

env:
  PROJECT_ID: build-project-476008
  REGION: europe-north2
  GAR_LOCATION: europe-north2-docker.pkg.dev/build-project-476008/monitoring 
  TF_VAR_project_id: ${{ env.PROJECT_ID }}
  TF_VAR_location: ${{ env.LOCATION}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA }}' 
      
      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Apply
        run: terraform apply --auto-approve

  build-push-artifact:
    runs-on: ubuntu-latest
    strategy:
      # Define the loop inputs here
      matrix:
        include:
          - context_path: ./node_exporter
            image_name: node
          - context_path: ./grafana
            image_name: graf
          - context_path: ./prometheus
            image_name: prom
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA}}' 

      - name: Login to Google Regiestery
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}
          username: _json_key
          password: ${{ secrets.GCP_SA }} 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v6
        with:
          # The context changes based on the matrix
          context: ${{ matrix.context_path }} 
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}/${{ matrix.image_name }}:latest
            ${{ env.GAR_LOCATION }}/${{ matrix.image_name }}:${{ github.sha }}
      
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./v1
      #     push: true
      #     tags: |
      #       ${{ env.GAR_LOCATION }}/node:latest
      #       ${{ env.GAR_LOCATION }}/node:${{ github.sha }}